/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AutemInterface extends ethers.utils.Interface {
  functions: {
    "beneficiary()": FunctionFragment;
    "execute(address,uint256,bytes)": FunctionFragment;
    "lastPing()": FunctionFragment;
    "metadata()": FunctionFragment;
    "owner()": FunctionFragment;
    "setBeneficiary(address)": FunctionFragment;
    "setMetadata(string)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setWindow(uint96)": FunctionFragment;
    "setup(address,address,uint96,string)": FunctionFragment;
    "window()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "lastPing", values?: undefined): string;
  encodeFunctionData(functionFragment: "metadata", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBeneficiary",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setMetadata", values: [string]): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "window", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastPing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metadata", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setWindow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "window", data: BytesLike): Result;

  events: {
    "Call(bool,bytes)": EventFragment;
    "Ping()": EventFragment;
    "SetBeneficiary(address)": EventFragment;
    "SetOwner(address)": EventFragment;
    "SetWindow(uint96)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Call"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Ping"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetBeneficiary"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetWindow"): EventFragment;
}

export class Autem extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AutemInterface;

  functions: {
    beneficiary(overrides?: CallOverrides): Promise<[string]>;

    "beneficiary()"(overrides?: CallOverrides): Promise<[string]>;

    execute(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "execute(address,uint256,bytes)"(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    lastPing(overrides?: CallOverrides): Promise<[BigNumber]>;

    "lastPing()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    metadata(overrides?: CallOverrides): Promise<[string]>;

    "metadata()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    setBeneficiary(
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBeneficiary(address)"(
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setMetadata(
      _metadata: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMetadata(string)"(
      _metadata: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setOwner(
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setOwner(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setWindow(
      _window: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setWindow(uint96)"(
      _window: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setup(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setup(address,address,uint96,string)"(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    window(overrides?: CallOverrides): Promise<[BigNumber]>;

    "window()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  beneficiary(overrides?: CallOverrides): Promise<string>;

  "beneficiary()"(overrides?: CallOverrides): Promise<string>;

  execute(
    _to: string,
    _val: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "execute(address,uint256,bytes)"(
    _to: string,
    _val: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  lastPing(overrides?: CallOverrides): Promise<BigNumber>;

  "lastPing()"(overrides?: CallOverrides): Promise<BigNumber>;

  metadata(overrides?: CallOverrides): Promise<string>;

  "metadata()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  setBeneficiary(
    _beneficiary: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBeneficiary(address)"(
    _beneficiary: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setMetadata(
    _metadata: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMetadata(string)"(
    _metadata: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setOwner(_owner: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setOwner(address)"(
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setWindow(
    _window: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setWindow(uint96)"(
    _window: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setup(
    _owner: string,
    _beneficiary: string,
    _window: BigNumberish,
    _metadata: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setup(address,address,uint96,string)"(
    _owner: string,
    _beneficiary: string,
    _window: BigNumberish,
    _metadata: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  window(overrides?: CallOverrides): Promise<BigNumber>;

  "window()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    beneficiary(overrides?: CallOverrides): Promise<string>;

    "beneficiary()"(overrides?: CallOverrides): Promise<string>;

    execute(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "execute(address,uint256,bytes)"(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    lastPing(overrides?: CallOverrides): Promise<BigNumber>;

    "lastPing()"(overrides?: CallOverrides): Promise<BigNumber>;

    metadata(overrides?: CallOverrides): Promise<string>;

    "metadata()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    setBeneficiary(
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBeneficiary(address)"(
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetadata(_metadata: string, overrides?: CallOverrides): Promise<void>;

    "setMetadata(string)"(
      _metadata: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(_owner: string, overrides?: CallOverrides): Promise<void>;

    "setOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setWindow(_window: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setWindow(uint96)"(
      _window: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setup(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "setup(address,address,uint96,string)"(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    window(overrides?: CallOverrides): Promise<BigNumber>;

    "window()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    Call(_success: null, _result: null): EventFilter;

    Ping(): EventFilter;

    SetBeneficiary(_beneficiary: string | null): EventFilter;

    SetOwner(_owner: string | null): EventFilter;

    SetWindow(_window: null): EventFilter;
  };

  estimateGas: {
    beneficiary(overrides?: CallOverrides): Promise<BigNumber>;

    "beneficiary()"(overrides?: CallOverrides): Promise<BigNumber>;

    execute(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "execute(address,uint256,bytes)"(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    lastPing(overrides?: CallOverrides): Promise<BigNumber>;

    "lastPing()"(overrides?: CallOverrides): Promise<BigNumber>;

    metadata(overrides?: CallOverrides): Promise<BigNumber>;

    "metadata()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setBeneficiary(
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setBeneficiary(address)"(
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setMetadata(_metadata: string, overrides?: Overrides): Promise<BigNumber>;

    "setMetadata(string)"(
      _metadata: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setOwner(_owner: string, overrides?: Overrides): Promise<BigNumber>;

    "setOwner(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setWindow(_window: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "setWindow(uint96)"(
      _window: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setup(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setup(address,address,uint96,string)"(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    window(overrides?: CallOverrides): Promise<BigNumber>;

    "window()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    beneficiary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "beneficiary()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    execute(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "execute(address,uint256,bytes)"(
      _to: string,
      _val: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    lastPing(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lastPing()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    metadata(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "metadata()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBeneficiary(
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBeneficiary(address)"(
      _beneficiary: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setMetadata(
      _metadata: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMetadata(string)"(
      _metadata: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setOwner(
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setOwner(address)"(
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setWindow(
      _window: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setWindow(uint96)"(
      _window: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setup(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setup(address,address,uint96,string)"(
      _owner: string,
      _beneficiary: string,
      _window: BigNumberish,
      _metadata: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    window(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "window()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
